/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import { meshBounds } from "@react-three/drei";
import { BoxGeometry, Raycaster } from "three";

export default function Wall(props) {
  const wallRef2 = useRef(null)
  const capybaraLeft = useTexture("/static/capybaraLeft.jpg")
  const capybaraRight = useTexture("/static/capybaraRight.jpg")
  const [imagen, setImagen] = useState(false)
  const estadoFoto = (event) => {
    if (imagen) {
      wallRef2.current.children[0].children[0].material.map = capybaraLeft
    } else {
      wallRef2.current.children[0].children[0].material.map = capybaraRight
    }
  }
  return (
    <group ref={wallRef2} {...props} dispose={null} onDoubleClick={estadoFoto}>
      <mesh scale={0.75} raycast={meshBounds} onDoubleClick={(e) => {
        setImagen(!imagen)
      }}>
        <mesh scale={4} rotation-y={Math.PI / 1.2} >
          <planeGeometry />
          <meshBasicMaterial map={capybaraRight} />
        </mesh>
      </mesh>
    </group>
  );
}
